// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
}
export {}
