// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseMap: typeof import('./src/components/BaseMap.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    MapBar: typeof import('./src/components/MapBar.vue')['default']
    MapOpPopover: typeof import('./src/components/MapOpPopover.vue')['default']
    MapRender: typeof import('./src/components/MapRender.vue')['default']
    MindMap: typeof import('./src/components/MindMap.vue')['default']
    Note: typeof import('./src/components/Note.vue')['default']
    NotePopover: typeof import('./src/components/NotePopover.vue')['default']
    OperatePopover: typeof import('./src/components/OperatePopover.vue')['default']
    ProfilePopover: typeof import('./src/components/ProfilePopover.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RectMap: typeof import('./src/components/RectMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}

export {}
