// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    DocPopover: typeof import('./src/components/DocPopover.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Map: typeof import('./src/components/map/Map.vue')['default']
    Map1: typeof import('./src/components/map/Map1.vue')['default']
    MapBar: typeof import('./src/components/map/MapBar.vue')['default']
    MapOpPopover: typeof import('./src/components/map/MapOpPopover.vue')['default']
    MapRender: typeof import('./src/components/map/MapRender.vue')['default']
    Note: typeof import('./src/components/note/Note.vue')['default']
    NotePopover: typeof import('./src/components/note/NotePopover.vue')['default']
    ProfilePopover: typeof import('./src/components/ProfilePopover.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}

export {}
